pull_request_rules:
  - name: Automatic merge for dependabot when everything passes
    conditions:
    - and:
        - author~=^dependabot
        - check-success-or-neutral=Better Code Hub
        - "check-success-or-neutral=LGTM analysis: Python"
        - check-success-or-neutral=run-tests (3.7)
        - check-success-or-neutral=run-tests (3.8)
        - check-success-or-neutral=run-tests (3.9)
        - check-success-or-neutral=run-tests (3.10)
        - check-success-or-neutral=coverage/coveralls
    actions:
      merge:
        method: merge